spring:
  profiles:
    active: dev

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mariadb://localhost:3306/ledger
    username: ledger
    password: ledgerpw
  jpa:
    hibernate:
      ddl-auto: update   # 개발 중만 사용, 운영은 validate
    properties:
      hibernate:
        format_sql: true
        jdbc.time_zone: UTC
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

server:
  port: 8080